### ISSUE TITLE
Error while accessing provider:com.github.cheeriotb.isdrap.provider

### ISSUE THREAD

**Issue by r00tb33** [cheeriotb/ISD-R-AccessProvider#2]
Hello,

I've compiled the apk and moved the files to the necessary folders in /system but I am stuck at the following error:

```
$ adb shell content query --uri content://com.github.cheeriotb.isdrap.provider/store/BF2D075C059F709295B6
Error while accessing provider:com.github.cheeriotb.isdrap.provider
java.lang.IllegalStateException: Could not find provider: com.github.cheeriotb.isdrap.provider
	at com.android.commands.content.Content$Command.execute(Content.java:467)
	at com.android.commands.content.Content.main(Content.java:690)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
```
What could be the issue? 

Awaiting to hear from you!!

**Comment by cheeriotb** [comment]
I am sorry, but I have no test environment for checking your issue now. It looks that the content provider is not recognized by the system correctly. Is there anything different from the description like the mobile phone or OS version?

**Comment by r00tb33** [comment]
> I am sorry, but I have no test environment for checking your issue now. It looks that the content provider is not recognized by the system correctly. Is there anything different from the description like the mobile phone or OS version?

Hi @cheeriotb ,

Thanks for the response!!

I am testing the app on a Pixel 3a running on top of Android 10. But, my current build is not a user-debug build rather a AOSP image form google repo.

Is it mandatory to have a user-debug build? I am facing issues creating folders in /system partition so had to downgrade to Android 9.

Awaiting to hear from you!!
